param_node:
  ros__parameters:
    traj_duration: 8.0
    acc_duration: 2.0
    total_time: 8.0
    trajectory_len: 200
    Kp: 20
    end_position_vec: [0.4, 0.3, 0.5]
    lambda: 20.0

action_server_node:
  ros__parameters:
    cmd_interface: "velocity"
    traj_duration: 8.0
    acc_duration: 2.0
    total_time: 8.0
    trajectory_len: 200
    Kp: 20
    end_position_vec: [0.4, 0.3, 0.5]
    lambda: 20.0

    

